name: Build and Release Barebones Shell

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to use"
        required: true
        default: "main"

jobs:
  run_on_windows_x64:
    runs-on: Windows_x64_8cores
    outputs:
      artifact-name: barebones_shell_x64_exe
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies and build x64 exe
        env:
          BOT_REPO_ACCESS: ${{ secrets.BOT_REPO_ACCESS }}
        run: |
          echo "Verifying Python installation..."
          python --version

          $env:Path += ";c:\python312\Scripts"
          $env:PYTHONUTF8 = 1

          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade inductiva pyinstaller prompt_toolkit truststore

          if ("${{ github.ref }}" -eq "refs/heads/main") {
            $env:INDUCTIVA_API_KEY = "${{ secrets.API_TEST_KEY }}"
          } else {
            $env:INDUCTIVA_API_KEY = "${{ secrets.API_DEV_TEST_KEY }}"
            $env:INDUCTIVA_API_URL = "https://api-dev.inductiva.ai"
          }

          cd barebones-shell

          pyinstaller barebones_shell.py --name barebones_shell_x64 --icon=favicon.ico --additional-hooks-dir=. --onefile

      - name: Upload x64 executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: barebones_shell_x64
          path: barebones-shell/dist/barebones_shell_x64.exe

  release:
    needs: [run_on_windows_x64]
    runs-on: ubuntu-latest
    steps:
      - name: Download ARM64 executable artifact
        uses: actions/download-artifact@v3
        with:
          name: barebones_shell_arm64
          path: ./release_assets

      - name: Download x64 executable artifact
        uses: actions/download-artifact@v3
        with:
          name: barebones_shell_x64
          path: ./release_assets

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload ARM64 exe to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/barebones_shell_arm64.exe
          asset_name: barebones_shell_arm64.exe
          asset_content_type: application/octet-stream

      - name: Upload x64 exe to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release_assets/barebones_shell_x64.exe
          asset_name: barebones_shell_x64.exe
          asset_content_type: application/octet-stream
